<a href="https://colab.research.google.com/github/Josee0002/Machine_Learning/blob/main/Training_Hate_profiles_BoW%26BoN_g_Softmax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Jose Ángel Pertuz Montes**
# **Miguel Ángel Banda del Valle**

**Conectar con Drive** - Acceder a datos preprocesados

In [1]:
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

Mounted at /content/drive


In [2]:
import sys
sys.path.append('/content/drive/MyDrive/ColabNotebooks/')

In [3]:
import re
import nltk
import spacy
import unicodedata
from nltk import TweetTokenizer
from spacy.lang.es import Spanish
from spacy.lang.en import English
from nltk.util import ngrams


class TextProcessing(object):
    name = 'Text Processing'
    lang = 'es'

    def __init__(self, lang: str = 'es'):
        self.lang = lang

    @staticmethod
    def proper_encoding(text: str):
        result = ''
        try:
            text = unicodedata.normalize('NFD', text)
            text = text.encode('ascii', 'ignore')
            result = text.decode("utf-8")
        except Exception as e:
            print('Error proper_encoding: {0}'.format(e))
        return result

    @staticmethod
    def stopwords(text: str):
        result = ''
        try:
            nlp = Spanish()if TextProcessing == 'es' else English()
            doc = nlp(text)
            token_list = [token.text for token in doc]
            sentence = []
            for word in token_list:
                lexeme = nlp.vocab[word]
                if not lexeme.is_stop:
                    sentence.append(word)
            result = ' '.join(sentence)
        except Exception as e:
            print('Error stopwords: {0}'.format(e))
        return result

    @staticmethod
    def remove_patterns(text: str):
        result = ''
        try:
            text = re.sub(r'\©|\×|\⇔|\_|\»|\«|\~|\#|\$|\€|\Â|\�|\¬', '', text)
            text = re.sub(r'\,|\;|\:|\!|\¡|\’|\‘|\”|\“|\"|\'|\`', '', text)
            text = re.sub(r'\}|\{|\[|\]|\(|\)|\<|\>|\?|\¿|\°|\|', '', text)
            text = re.sub(r'\/|\-|\+|\*|\=|\^|\%|\&|\$', '', text)
            text = re.sub(r'\b\d+(?:\.\d+)?\s+', '', text)
            result = text.lower()
        except Exception as e:
            print('Error remove_patterns: {0}'.format(e))
        return result

    @staticmethod
    def transformer(text: str, stopwords: bool = False):
        result = ''
        try:
            text_out = TextProcessing.proper_encoding(text)
            text_out = text_out.lower()
            text_out = re.sub("[\U0001f000-\U000e007f]", '[EMOJI]', text_out)
            text_out = re.sub(
                r'(?i)\b((?:https?://|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}/)(?:[^\s()<>]+|\(([^\s()<>]+'
                r'|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:\'".,<>?«»“”‘’]))',
                '[URL]', text_out)
            text_out = re.sub("@([A-Za-z0-9_]{1,40})", '[MENTION]', text_out)
            text_out = re.sub("#([A-Za-z0-9_]{1,40})", '[HASTAG]', text_out)
            text_out = TextProcessing.remove_patterns(text_out)
            # text_out = TextAnalysis.lemmatization(text_out) if lemmatizer else text_out
            text_out = TextProcessing.stopwords(text_out) if stopwords else text_out
            text_out = re.sub(r'\s+', ' ', text_out).strip()
            text_out = text_out.rstrip()
            result = text_out if text_out != ' ' else None
        except Exception as e:
            print('Error transformer: {0}'.format(e))
        return result

    @staticmethod
    def tokenizer(text: str):
        val = []
        try:
            text_tokenizer = TweetTokenizer()
            val = text_tokenizer.tokenize(text)
        except Exception as e:
            print('Error make_ngrams: {0}'.format(e))
        return val

    @staticmethod
    def make_ngrams(text: str, num: int):
        result = ''
        try:
            n_grams = ngrams(nltk.word_tokenize(text), num)
            result = [' '.join(grams) for grams in n_grams]
        except Exception as e:
            print('Error make_ngrams: {0}'.format(e))
        return result

In [30]:
def stopwords(text: str):
        result = ''
        try:
            nlp = Spanish()if TextProcessing == 'es' else English()
            doc = nlp(text)
            token_list = [token.text for token in doc]
            sentence = []
            for word in token_list:
                lexeme = nlp.vocab[word]
                if not lexeme.is_stop:
                    sentence.append(word)
            result = ' '.join(sentence)
        except Exception as e:
            print('Error stopwords: {0}'.format(e))
        return result

def transformer(text: str, stopwords: bool = False):
        result = ''
        try:
            text_out = TextProcessing.proper_encoding(text)
            text_out = text_out.lower()
            text_out = re.sub("[\U0001f000-\U000e007f]", '[EMOJI]', text_out)
            text_out = re.sub(
                r'(?i)\b((?:https?://|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}/)(?:[^\s()<>]+|\(([^\s()<>]+'
                r'|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:\'".,<>?«»“”‘’]))',
                '[URL]', text_out)
            text_out = re.sub("@([A-Za-z0-9_]{1,40})", '[MENTION]', text_out)
            text_out = re.sub("#([A-Za-z0-9_]{1,40})", '[HASTAG]', text_out)
            text_out = TextProcessing.remove_patterns(text_out)
            # text_out = TextAnalysis.lemmatization(text_out) if lemmatizer else text_out
            text_out = TextProcessing.stopwords(text_out) if stopwords else text_out
            text_out = re.sub(r'\s+', ' ', text_out).strip()
            text_out = text_out.rstrip()
            result = text_out if text_out != ' ' else None
        except Exception as e:
            print('Error transformer: {0}'.format(e))
        return result
def make_ngrams(text: str, num: int):
        result = ''
        try:
            n_grams = ngrams(nltk.word_tokenize(text), num)
            result = [' '.join(grams) for grams in n_grams]
        except Exception as e:
            print('Error make_ngrams: {0}'.format(e))
        return result

In [32]:
import io
import sys
import os
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import nltk
from collections import Counter
from sklearn.preprocessing import LabelEncoder 
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix

In [6]:
le = LabelEncoder()

In [7]:
raw_data = pd.read_csv('/content/drive/MyDrive/Datasets/Hate_Profile.csv', sep=';')
raw_data

Id  ... polarity
0      0035a3060d075506f5b9b978a910aa1f  ...        0
1      0035a3060d075506f5b9b978a910aa1f  ...        0
2      0035a3060d075506f5b9b978a910aa1f  ...        0
3      0035a3060d075506f5b9b978a910aa1f  ...        0
4      0035a3060d075506f5b9b978a910aa1f  ...        0
...                                 ...  ...      ...
39995  fde1d7437a12068e0e39505af6948f99  ...        1
39996  fde1d7437a12068e0e39505af6948f99  ...        1
39997  fde1d7437a12068e0e39505af6948f99  ...        1
39998  fde1d7437a12068e0e39505af6948f99  ...        1
39999  fde1d7437a12068e0e39505af6948f99  ...        1

[40000 rows x 3 columns]

In [36]:
raw=[]
Id=[] 
comment=[]
polarity=[]
for i in range(200):
  Id.append(raw_data['Id'][200*i])
  polarity.append(raw_data['polarity'][200*i])
  comment_sub=[]
  for j in range(200):
    comment_sub.append(raw_data['comment'][j+200*i])
  b=np.transpose(comment_sub)
  comment.append(b)

In [49]:
comment

[array([' pasta con bichos de agua',
        'De verdad puto lol de mierda qué asco de juego joder',
        '  me hice una pcr y ya tengo los resultados! menos mal ',
        'Y un lomo queso de baguette entera, tranqui ',
        'Me cambio de curro y me llegan 3 ofeas directas, esto es de cachondeo',
        '  Preferiría unos electrodos en los cojones a estar en la piel de Antonio Baños ahora mismo',
        'Dksksksksk en qué paida presupuestaria creéis que han colado los sobrecitos que han volado? ',
        ' En medio de la nada treballo skdkdk',
        '  Seguid viendo telebasura, otros aprovecharemos el tiempo estudiando a Hegel y metiendonos cocaína',
        'VIKINGOS! La puta mejor serie 👊😜',
        '  oye vosotros os la pasabais por la cara cuando estaba nueva?',
        'Ayer no me comí el bocata porque no tenía hambre y hoy que me comería la cabeza de un dinosaurio me lo he dejado en casa 😭',
        'Y me voy, como que me siento super culpable. En serio putísima mierd

In [50]:
np.shape(comment)

(200, 200)

In [8]:
y = le.fit_transform(raw_data['polarity'])
y

array([0, 0, 0, ..., 1, 1, 1])

# **Bag of Words**

In [9]:
corpus = [transformer(row) for row in raw_data['comment'].tolist()]
bow = CountVectorizer(analyzer='word', ngram_range=(1, 1))
x = bow.fit_transform(corpus)

In [10]:
#df = pd.DataFrame(x.toarray(),
#                 index=['content '+str(i) for i in range(1, 1+len(corpus))],
#                 columns=bow.get_feature_names())

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=40)

In [12]:
softmax = LogisticRegression(multi_class="multinomial", solver="lbfgs", C=10, max_iter=200)
softmax.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=10, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=200,
                   multi_class='multinomial', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [13]:
y_predict = softmax.predict(x_test)
confusion_matrix(y_test, y_predict, labels=[0, 1])

array([[3264, 1746],
       [1744, 3246]])

In [14]:
classification = classification_report(y_test, y_predict)
print(classification)

              precision    recall  f1-score   support

           0       0.65      0.65      0.65      5010
           1       0.65      0.65      0.65      4990

    accuracy                           0.65     10000
   macro avg       0.65      0.65      0.65     10000
weighted avg       0.65      0.65      0.65     10000



# **Bag of N-grams**

In [35]:
corpus = [transformer(row) for row in raw_data['comment'].tolist()]
bow = CountVectorizer(analyzer='word', ngram_range=(1, 3))
x = bow.fit_transform(corpus)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=40)
softmax = LogisticRegression(multi_class="multinomial", solver="lbfgs", C=10, max_iter=200)
softmax.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=10, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=200,
                   multi_class='multinomial', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [28]:
y_predict = softmax.predict(x_test)
confusion_matrix(y_test, y_predict, labels=[0, 1])

array([[3378, 1632],
       [1676, 3314]])

In [29]:
classification = classification_report(y_test, y_predict)
print(classification)

              precision    recall  f1-score   support

           0       0.67      0.67      0.67      5010
           1       0.67      0.66      0.67      4990

    accuracy                           0.67     10000
   macro avg       0.67      0.67      0.67     10000
weighted avg       0.67      0.67      0.67     10000

